---
title: "instacart_again"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r message=FALSE, warning=FALSE, results='hide'}
library(data.table)
library(dplyr)
library(ggplot2)
library(knitr)
library(stringr)
library(DT)
```

## Including Plots
You can also embed plots, for example:

```{r pressure, echo=FALSE}

plot(pressure)
```
Reading files into data.table 
```{r}
getwd()
### Read in the data
orders <- fread("Great Lakes/instacart/data/orders.csv")
products <- fread('Great Lakes/instacart/data/products.csv')
order_products_train <- fread('Great Lakes/instacart/data/order_products__train.csv')
order_products_prior <- fread('Great Lakes/instacart/data/order_products__prior.csv')
aisles <- fread('Great Lakes/instacart/data/aisles.csv')
departments <- fread('Great Lakes/instacart/data/departments.csv')


str(orders)
str(order_products_prior)
str(products)
```

changing id fields into factos
```{r}
orders <- orders %>% mutate(order_hour_of_day = as.numeric(order_hour_of_day), eval_set = as.factor(eval_set))
products$product_name <- as.factor(products$product_name)
str(products)
```

Peak traffic time
```{r}
##orders %>% 
prior_order = orders[orders$eval_set=="prior",]

peak_traffic <- prior_order %>% 
  count(order_hour_of_day,order_dow)
head(peak_traffic)
# Peak hours
prior_order %>% 
  ggplot(aes(x=order_hour_of_day)) +
  geom_histogram(stat="count",fill="blue")

# Weekly maximum
weekly_max = peak_traffic %>% 
  group_by(order_dow) %>% 
  summarise(Max=max(n)) 


head(peak_traffic_new)

pt_plot1 <- peak_traffic %>%
  ggplot(aes(x=order_hour_of_day,y = n,group=order_dow,color=order_dow)) +
  geom_line()  

pt_plot1 + facet_wrap(~ order_dow)+
  stat_summary(fun.y = "max",geom = "point",size=3)



?ggplot

# Peak days of the week 
prior_order %>% 
  ggplot(aes(x=order_dow)) +
  geom_line(stat="count",fill="blue")

```

